namespace STS2AIAgent.Tests;

/// <summary>
/// One state build owns both halves of a decision -- the compact state and the exact action
/// descriptors generated by that same action-surface enumeration.
/// </summary>
/// <remarks>
/// A caller that reads <c>GET /state</c> and then <c>GET /actions/available</c> makes two requests,
/// and between them the game can advance. The two answers then describe two different frames: a
/// screen change mid-request left the index validator judging an action against a hand the payload
/// it validated had never shown. <c>GameStateService.BuildDecisionSnapshotPayload</c> is the one
/// read that cannot do that, because it retains the descriptors <c>BuildStatePayload</c> already
/// enumerated on the payload it returns (internal, so they never reach the raw <c>/state</c> wire
/// shape) instead of enumerating the action surface again.
///
/// This contract pins the three things that could quietly undo it:
///
/// * the state build walks the action surface once, and the descriptor list it keeps is the one that
///   walk produced;
/// * the snapshot builder builds the state once and never consults <c>/actions/available</c>'s own
///   builder, the second enumeration that shipped here;
/// * both the in-process bridge (<c>GameBridge</c>, what the native MCP <c>act</c>/<c>decide</c>
///   read) and the ordinary HTTP route go through that builder rather than coordinating two reads.
/// </remarks>
internal static class DecisionSnapshotContractTests
{
    private const string NamesDeclaration = "private static string[] BuildAvailableActionNames(";

    public static void OneStateBuildEnumeratesTheActionSurfaceOnce()
    {
        var source = AgentSourceFixture.ReadStateService();
        var build = Flat(AgentSourceFixture.MethodBody(source, "BuildStatePayload"));
        var names = Flat(AgentSourceFixture.DeclarationBody(
            source,
            "private static string[] BuildAvailableActionNames("));

        // The walk lives in the names projection, reached from the state build. Reading the two
        // together is the point: a second walk could only appear in one of them.
        Assert.Contains("EnumerateAvailableActions(currentScreen,combatState,runState,combatActionGate)", names, StringComparison.Ordinal);
        Assert.Equal(
            1,
            Occurrences(build, "EnumerateAvailableActions(") + Occurrences(names, "EnumerateAvailableActions("));

        // The signature is not part of the body, so the hand-back is read from the declaration's own
        // text -- the state build cannot keep descriptors it was never handed.
        var declaration = source[source.IndexOf(NamesDeclaration, StringComparison.Ordinal)..];
        var signature = declaration[..declaration.IndexOf('{')];
        Assert.Contains("out ActionDescriptor[] descriptors", signature, StringComparison.Ordinal);

        // What the projection keeps is the walk's own descriptor list, not a name list the snapshot
        // builder would have to re-derive the descriptors from.
        Assert.Contains(
            "descriptors=EnumerateAvailableActions(currentScreen,combatState,runState,combatActionGate).ToArray();",
            names,
            StringComparison.Ordinal);
        Assert.Contains("names[index]=descriptors[index].name;", names, StringComparison.Ordinal);
    }

    public static void TheSnapshotBuilderReadsTheStateOnceAndNothingElse()
    {
        var source = AgentSourceFixture.ReadStateService();
        var snapshot = Flat(AgentSourceFixture.MethodBody(source, "BuildDecisionSnapshotPayload"));

        Assert.Equal(1, Occurrences(snapshot, "BuildStatePayload("));
        // The bug this replaces: a state build followed by a separate action-surface build, each its
        // own read. Neither may come back into this method.
        Assert.False(
            snapshot.Contains("BuildAvailableActionsPayload(", StringComparison.Ordinal),
            "BuildDecisionSnapshotPayload must take the descriptors from the state build it just made, "
            + "not enumerate the action surface again -- that second read is the frame skew.");
        Assert.False(
            snapshot.Contains("EnumerateAvailableActions(", StringComparison.Ordinal),
            "BuildDecisionSnapshotPayload must not walk the action surface itself.");
        Assert.Contains("state=state.agent_view??state", snapshot, StringComparison.Ordinal);
        Assert.Contains("available_actions=state.AvailableActionDescriptors", snapshot, StringComparison.Ordinal);
    }

    /// <summary>
    /// The retained descriptors are internal state, never part of the raw <c>/state</c> wire shape.
    /// </summary>
    /// <remarks>
    /// <c>GameStatePayload</c> is the documented <c>/state</c> contract, so a descriptor array that
    /// reached the wire would be an undocumented field on every state read -- exactly what the
    /// api-facts gate exists to refuse. <c>System.Text.Json</c> writes public properties only, and
    /// both source parsers behind that gate read <c>public</c> declarations only, so an
    /// <c>internal</c> property satisfies both. This asserts the modifier rather than the absence of
    /// the name, because the name is what the snapshot builder reads.
    /// </remarks>
    public static void TheDescriptorCacheIsNotAWireField()
    {
        var payloads = AgentSourceFixture.Read("STS2AIAgent/Game/GameStateService.Payloads.cs");
        var state = AgentSourceFixture.DeclarationBody(payloads, "internal sealed class GameStatePayload");

        Assert.Contains(
            "internalActionDescriptor[]AvailableActionDescriptors{get;init;}",
            Flat(state),
            StringComparison.Ordinal);
        Assert.False(
            state.Contains("public ActionDescriptor[] AvailableActionDescriptors", StringComparison.Ordinal),
            "AvailableActionDescriptors must stay internal: a public property would serialize into every "
            + "raw /state response and become an undocumented wire field.");
    }

    public static void TheHttpRouteServesTheSnapshotInOneGameThreadTurn()
    {
        var router = AgentSourceFixture.Read("STS2AIAgent/Server/Router.cs");
        var block = AgentSourceFixture.DeclarationBody(router, "public static async Task HandleAsync(");

        var marker = block.IndexOf("\"/decision-snapshot\"", StringComparison.Ordinal);
        Assert.True(marker >= 0, "Router no longer serves GET /decision-snapshot");

        // The route's own handler runs to the next `return;` -- one invocation, one builder.
        var tail = block[marker..];
        var end = tail.IndexOf("return;", StringComparison.Ordinal);
        Assert.True(end >= 0, "the /decision-snapshot branch no longer returns");
        var handler = Flat(tail[..end]);

        Assert.Equal(1, Occurrences(handler, "GameThread.InvokeAsync("));
        Assert.Contains("GameThread.InvokeAsync(GameStateService.BuildDecisionSnapshotPayload)", handler, StringComparison.Ordinal);
        Assert.False(
            handler.Contains("BuildStatePayload", StringComparison.Ordinal)
            || handler.Contains("BuildAvailableActionsPayload", StringComparison.Ordinal),
            "the /decision-snapshot route must make one game-thread call into the snapshot builder, not "
            + "coordinate two reads of its own.");
    }

    public static void TheBridgeSerializesTheSnapshotBuilder()
    {
        var bridge = AgentSourceFixture.Read("STS2AIAgent/Agent/GameBridge.cs");
        var body = Flat(AgentSourceFixture.MethodBody(bridge, "GetActionSnapshotJsonAsync"));

        Assert.Contains("GameStateService.BuildDecisionSnapshotPayload()", body, StringComparison.Ordinal);
        Assert.Equal(1, Occurrences(body, "GameThread.InvokeAsync("));
        Assert.False(
            body.Contains("BuildStatePayload", StringComparison.Ordinal)
            || body.Contains("BuildAvailableActionsPayload", StringComparison.Ordinal),
            "the in-process action snapshot must come from the one-snapshot builder; building the state "
            + "and the action surface separately is the two-read shape this replaced.");
    }

    private static string Flat(string source) => AgentSourceFixture.WithoutWhitespace(source);

    private static int Occurrences(string source, string value)
    {
        var count = 0;
        var index = source.IndexOf(value, StringComparison.Ordinal);
        while (index >= 0)
        {
            count++;
            index = source.IndexOf(value, index + value.Length, StringComparison.Ordinal);
        }

        return count;
    }
}
