#!/usr/bin/env python3
"""Offline verification gates for dependency security, API documentation, and archived docs.

Run from the repository root:

    python scripts/check_verification_gates.py
    python scripts/check_verification_gates.py --only api-doc

Gates
-----
lockfile   Dependency security floors plus manifest/lock agreement. Prevents the
           advisories closed for fastmcp (CVE-2026-32871) and fast-uri
           (CVE-2026-13676) from silently regressing on a future lock refresh.
api-doc    Every action the mod accepts in POST /action must appear in the
           action contract block in docs/api.md, and the block must not list
           actions the code no longer supports.
api-facts  Facts that docs/api.md states and that code owns must still agree:
           the documented `mod_version` against mod_manifest.json, the screen
           enum against the screens GameStateService.ResolveNonModalScreen can
           emit, and the documented default port against HttpServer.DefaultPort.
           The action contract only covers action names, so these would
           otherwise drift silently on the next version bump or screen change.
doc-marks  Date-stamped validation records must carry a historical marker, and
           archived topic pages must keep their redirect to history/.
docs-tracked
           Every Markdown page under docs/ must be tracked by git. docs/ used to
           be gitignored, so a new page could be written, pass the local
           doc-marks gate, and still be missing from every fresh checkout --
           which is what CI builds from.
script-encoding
           PowerShell scripts containing non-ASCII text must carry a UTF-8 BOM.

Exit code 0 means every selected gate passed. Exit code 1 means at least one
gate failed and the failure detail has been printed to stderr. Standard library
only: preflight invokes this with the system Python.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

# --- Gate configuration -----------------------------------------------------

# Minimum safe versions. Each entry names the advisory it protects against.
SECURITY_FLOORS: dict[str, tuple[str, str]] = {
    # package -> (minimum safe version, advisory)
    "fastmcp": ("3.2.0", "CVE-2026-32871 (issue #50)"),
    "fast-uri": ("3.1.6", "CVE-2026-13676 (issue #51)"),
}

# Locks are regenerated by tooling; these overrides must survive a refresh.
REQUIRED_NPM_OVERRIDES = {"yauzl": "3.2.1"}

# Files that must exist for the targets below to mean anything. Deliberately tracked
# files only: AGENTS.md is gitignored and therefore absent from a fresh checkout, which
# is exactly the environment CI runs the gates in.
ROOT_SENTINELS = ("STS2AIAgent/mod_manifest.json", "mcp_server/pyproject.toml")

API_CONTRACT_BEGIN = "<!-- BEGIN ACTION CONTRACT -->"
API_CONTRACT_END = "<!-- END ACTION CONTRACT -->"

# --- api-facts sources of truth --------------------------------------------

# The health example claims a mod version; docs/api.md itself says the value tracks the
# mod, so the manifest is the thing it has to agree with.
MOD_VERSION_PATTERN = re.compile(r'"mod_version"\s*:\s*"([^"]+)"')
MANIFEST_VERSION_PATH = "STS2AIAgent/mod_manifest.json"

# The "## Screen 枚举" table is the client-facing screen vocabulary.
SCREEN_SECTION_HEADING = "## Screen 枚举"
DOC_SCREEN_ROW = re.compile(r"^\|\s*\`([A-Z][A-Z0-9_]*)\`", re.MULTILINE)

# GameStateService.ResolveNonModalScreen is the single producer of these names: early
# guards `return "X";`, then the switch expression's `=> "X"` arms.
RESOLVE_SCREEN_SIGNATURE = "private static string ResolveNonModalScreen(IScreenContext? currentScreen)"
CODE_SCREEN_SWITCH_ARM = re.compile(r'=>\s*"([A-Z][A-Z0-9_]*)"')
CODE_SCREEN_EARLY_RETURN = re.compile(r'return\s+"([A-Z][A-Z0-9_]*)"')
# A near-total parse failure (renamed method, rewritten in another style) must fail loudly
# instead of silently reading as "no screens to check".
MIN_CODE_SCREENS = 20

CODE_DEFAULT_PORT = re.compile(r"private\s+const\s+int\s+DefaultPort\s*=\s*(\d+)\s*;")
DOC_DEFAULT_PORT = re.compile(r"默认[^\n]*127\.0\.0\.1:(\d+)")
HTTP_SERVER_PATH = "STS2AIAgent/Server/HttpServer.cs"

# A date-stamped record inside docs/ is a snapshot, not a statement about today.
DATED_DOC_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}")
HISTORICAL_MARKERS = ("历史快照", "Historical snapshot")

# Snapshots whose filename carries no date, so the pattern above cannot find them. They are
# listed explicitly to keep the marker from being quietly dropped.
REQUIRED_SNAPSHOT_MARKERS = {
    "docs/mechanic-coverage-matrix.md": "its release-candidate conclusion belongs to the v0.98.3 build it was written against",
}

# Archived topic pages keep their old path working as a redirect.
REQUIRED_REDIRECTS = {
    "docs/sts2-coverage-gaps.md": "history/sts2-coverage-gaps_2026-03-10.md",
}

# The docs/ directory used to be gitignored, so pages could be written that no fresh
# checkout (and therefore no CI run) would ever contain. Every page on disk has to be in
# the index instead. A source tarball has no .git and no index to compare against, so the
# check degrades to a printed skip there rather than inventing a failure.
DOCS_MARKDOWN_GLOB = "*.md"

# Windows PowerShell 5.1 — what `powershell` resolves to on the CI runner and on most developer
# machines — reads a BOM-less script with the machine's ANSI code page. The same bytes therefore
# decode differently per locale: the UTF-8 bytes of a dash are harmless on a GBK machine and become
# a smart closing quote on CP1252, which ends the string early and makes the whole file a parse
# error. A UTF-8 BOM removes the ambiguity, so non-ASCII PowerShell scripts have to carry one.
SCRIPT_ENCODING_GLOBS = ("scripts/*.ps1",)
UTF8_BOM = b"\xef\xbb\xbf"


class GateError(Exception):
    """A verification gate failed."""


def parse_version(value: str) -> tuple[int, ...]:
    parts: list[int] = []
    for chunk in re.split(r"[.\-+]", value.strip()):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts) if parts else (0,)


def version_at_least(actual: str, minimum: str) -> bool:
    left, right = list(parse_version(actual)), list(parse_version(minimum))
    width = max(len(left), len(right))
    left += [0] * (width - len(left))
    right += [0] * (width - len(right))
    return tuple(left) >= tuple(right)


def read_text(repo_root: Path, relative: str) -> str:
    path = repo_root / relative
    if not path.is_file():
        raise GateError(f"missing required file: {relative}")
    return path.read_text(encoding="utf-8")


def parse_uv_lock(text: str) -> dict[str, str]:
    packages: dict[str, str] = {}
    name: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == "[[package]]":
            name = None
            continue
        match = re.match(r'^name = "([^"]+)"$', stripped)
        if match:
            name = match.group(1)
            continue
        match = re.match(r'^version = "([^"]+)"$', stripped)
        if match and name:
            packages.setdefault(name, match.group(1))
    return packages


def parse_pyproject_dependencies(text: str) -> list[str]:
    match = re.search(r"(?ms)^dependencies = \[(.*?)^\]", text)
    if not match:
        return []
    return re.findall(r'"([^"]+)"', match.group(1))


def dependency_name(specifier: str) -> str:
    return re.split(r"[<>=!~^\[;]", specifier, maxsplit=1)[0].strip()


def split_requirement(specifier: str) -> tuple[str, list[tuple[str, str]]]:
    """Split 'fastmcp>=3.1.0,<4.0.0' into ('fastmcp', [('>=', '3.1.0'), ('<', '4.0.0')])."""
    name = dependency_name(specifier)
    remainder = specifier[len(name):].split(";", maxsplit=1)[0]
    constraints: list[tuple[str, str]] = []
    for operator, version in re.findall(r"(~=|==|!=|<=|>=|\^|<|>)\s*([0-9][^,\s]*)", remainder):
        constraints.append((operator, version))
    return name, constraints


def satisfies(actual: str, constraints: list[tuple[str, str]]) -> bool:
    """PEP 440 subset: enough for the operators this project's manifests actually use."""
    for operator, required in constraints:
        left = parse_version(actual)
        right = parse_version(required)
        width = max(len(left), len(right))
        left += (0,) * (width - len(left))
        right += (0,) * (width - len(right))
        if operator == ">=" and not left >= right:
            return False
        if operator == ">" and not left > right:
            return False
        if operator == "<=" and not left <= right:
            return False
        if operator == "<" and not left < right:
            return False
        if operator == "==" and left != right:
            return False
        if operator == "!=" and left == right:
            return False
        if operator == "^":
            # npm caret: ^1.2.3 is >=1.2.3 and <2.0.0; ^0.2.3 is <0.3.0; ^0.0.3 pins exactly.
            if not left >= right:
                return False
            if right[0] > 0:
                upper = (right[0] + 1,)
            elif len(right) > 1 and right[1] > 0:
                upper = (0, right[1] + 1)
            else:
                return left == right
            padded = left + (0,) * max(0, len(upper) - len(left))
            if padded[: len(upper)] >= tuple(upper):
                return False
        if operator == "~=":
            # Compatible release: >= required, and the same up to the second-to-last part.
            if not left >= right:
                return False
            if len(right) >= 2 and left[: len(right) - 1] != right[: len(right) - 1]:
                return False
    return True


def flatten_overrides(overrides: dict) -> list[tuple[str, str]]:
    """npm overrides may be nested per parent package; flatten them to (package, pinned)."""
    flattened: list[tuple[str, str]] = []
    for key, value in overrides.items():
        if isinstance(value, str):
            flattened.append((key, value))
        elif isinstance(value, dict):
            flattened.extend(flatten_overrides(value))
    return flattened


def check_lockfile(repo_root: Path) -> list[str]:
    """Dependency floors and manifest/lock agreement."""
    notes: list[str] = []

    uv_lock = parse_uv_lock(read_text(repo_root, "mcp_server/uv.lock"))
    pyproject = read_text(repo_root, "mcp_server/pyproject.toml")

    for specifier in parse_pyproject_dependencies(pyproject):
        name, constraints = split_requirement(specifier)
        if not name:
            continue
        if name not in uv_lock:
            raise GateError(
                f"mcp_server/pyproject.toml declares '{name}' but mcp_server/uv.lock has no such package. "
                "Run 'uv lock' from mcp_server."
            )
        locked = uv_lock[name]
        if not satisfies(locked, constraints):
            raise GateError(
                f"mcp_server/uv.lock is out of sync with pyproject.toml: the manifest requires "
                f"'{specifier}' but the lock resolves {name} {locked}. Run 'uv lock' from mcp_server."
            )
        notes.append(f"uv.lock {name} {locked} satisfies '{specifier}'")

    for package, (minimum, advisory) in SECURITY_FLOORS.items():
        if package not in uv_lock:
            continue
        actual = uv_lock[package]
        if not version_at_least(actual, minimum):
            raise GateError(
                f"mcp_server/uv.lock pins {package} {actual}, below the safe floor {minimum} ({advisory})."
            )
        notes.append(f"uv.lock {package} {actual} >= {minimum}")

    lock_path = repo_root / "package-lock.json"
    manifest_path = repo_root / "package.json"
    if lock_path.is_file() and manifest_path.is_file():
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
        packages = lock.get("packages", {})
        for package, (minimum, advisory) in SECURITY_FLOORS.items():
            entry = packages.get(f"node_modules/{package}")
            if entry is None:
                continue
            actual = str(entry.get("version", ""))
            if not version_at_least(actual, minimum):
                raise GateError(
                    f"package-lock.json pins {package} {actual}, below the safe floor {minimum} ({advisory})."
                )
            notes.append(f"package-lock.json {package} {actual} >= {minimum}")

        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

        # The npm half of the manifest/lock agreement: every declared dependency must be
        # present in the lock at a version its range accepts.
        declared = dict(manifest.get("dependencies", {}))
        recorded = dict(packages.get("", {}).get("dependencies", {})) or dict(lock.get("dependencies", {}))
        for package, requirement in declared.items():
            if package not in recorded:
                raise GateError(
                    f"package.json declares '{package}' but package-lock.json does not record it. "
                    "Run 'npm install' from the repository root."
                )
            entry = packages.get(f"node_modules/{package}")
            if entry is None:
                raise GateError(
                    f"package.json declares '{package}' but package-lock.json has no resolved entry for it. "
                    "Run 'npm install' from the repository root."
                )
            actual = str(entry.get("version", ""))
            _, constraints = split_requirement(package + requirement)
            if not satisfies(actual, constraints):
                raise GateError(
                    f"package-lock.json is out of sync with package.json: the manifest requires "
                    f"'{package}{requirement}' but the lock resolves {actual}. "
                    "Run 'npm install' from the repository root."
                )
            notes.append(f"package-lock.json {package} {actual} satisfies '{package}{requirement}'")

        for package, pinned in flatten_overrides(manifest.get("overrides", {})):
            resolved = [
                str(entry.get("version", ""))
                for key, entry in packages.items()
                if re.search(rf"(^|/)node_modules/{re.escape(package)}$", key)
            ]
            if not resolved:
                raise GateError(
                    f"package.json overrides '{package}' to {pinned} but package-lock.json has no such entry."
                )
            below = sorted({item for item in resolved if not version_at_least(item, pinned)})
            if below:
                raise GateError(
                    f"package.json overrides '{package}' to {pinned} but package-lock.json still resolves {', '.join(below)}."
                )
            notes.append(f"override {package} {', '.join(sorted(set(resolved)))}")
            required = REQUIRED_NPM_OVERRIDES.get(package)
            if required and required not in resolved:
                raise GateError(
                    f"the required {package} override changed: expected {required}, package-lock.json resolves {', '.join(sorted(set(resolved)))}."
                )

    return notes


def parse_code_actions(repo_root: Path) -> set[str]:
    """Action names accepted by POST /action, read from the execute switch."""
    text = read_text(repo_root, "STS2AIAgent/Game/GameActionService.cs")
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if "return actionName switch" in line:
            start = index
            break
    if start is None:
        raise GateError("could not find 'return actionName switch' in STS2AIAgent/Game/GameActionService.cs")

    actions: set[str] = set()
    for line in lines[start + 1:]:
        if re.match(r"^\s*};\s*$", line):
            break
        match = re.match(r'^\s*"([a-z][a-z0-9_]*)"\s*=>', line)
        if match:
            actions.add(match.group(1))
    if not actions:
        raise GateError("the action switch in GameActionService.cs produced no action names")
    return actions


def parse_doc_actions(repo_root: Path) -> set[str]:
    """Action names declared in the docs/api.md contract block."""
    text = read_text(repo_root, "docs/api.md")
    begin = text.find(API_CONTRACT_BEGIN)
    end = text.find(API_CONTRACT_END)
    if begin < 0 or end < 0 or end <= begin:
        raise GateError(
            f"docs/api.md is missing the '{API_CONTRACT_BEGIN}' / '{API_CONTRACT_END}' action contract block."
        )
    block = text[begin + len(API_CONTRACT_BEGIN):end]
    actions = set(re.findall(r"^-\s*`([a-z][a-z0-9_]*)`", block, re.MULTILINE))
    if not actions:
        raise GateError("the docs/api.md action contract block lists no actions")
    return actions


def check_api_doc(repo_root: Path) -> list[str]:
    code = parse_code_actions(repo_root)
    documented = parse_doc_actions(repo_root)

    missing = sorted(code - documented)
    extra = sorted(documented - code)
    problems: list[str] = []
    if missing:
        problems.append("docs/api.md does not document these actions the mod accepts: " + ", ".join(missing))
    if extra:
        problems.append("docs/api.md documents these actions the mod does not accept: " + ", ".join(extra))
    if problems:
        raise GateError(" ".join(problems))
    return [f"{len(code)} actions match between GameActionService.cs and docs/api.md"]


def slice_section(text: str, heading: str, source: str) -> str:
    """Return the text between a level-2 heading and the next level-2 heading."""
    start = text.find(heading)
    if start < 0:
        raise GateError(f"{source} no longer contains the '{heading}' section")
    rest = text[start + len(heading):]
    following = re.search(r"^## ", rest, re.MULTILINE)
    return rest[: following.start()] if following else rest


def slice_method_body(text: str, signature: str, source: str) -> str:
    """Return the brace-matched body of a method, so literals elsewhere cannot leak in."""
    start = text.find(signature)
    if start < 0:
        raise GateError(f"{source} no longer declares '{signature}'")
    opening = text.find("{", start)
    if opening < 0:
        raise GateError(f"{source}: '{signature}' has no body brace")
    depth = 0
    for index in range(opening, len(text)):
        character = text[index]
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return text[opening:index]
    raise GateError(f"{source}: '{signature}' body braces never balanced")


def parse_code_screens(repo_root: Path) -> set[str]:
    """Screen names GameStateService.ResolveNonModalScreen can emit."""
    text = read_text(repo_root, "STS2AIAgent/Game/GameStateService.cs")
    body = slice_method_body(text, RESOLVE_SCREEN_SIGNATURE, "STS2AIAgent/Game/GameStateService.cs")
    screens = set(CODE_SCREEN_SWITCH_ARM.findall(body)) | set(CODE_SCREEN_EARLY_RETURN.findall(body))
    if len(screens) < MIN_CODE_SCREENS:
        raise GateError(
            "GameStateService.ResolveNonModalScreen yielded "
            f"{len(screens)} screen names, below the {MIN_CODE_SCREENS} expected. The extraction "
            "in check_verification_gates.py no longer matches the method; fix it before trusting "
            "this gate."
        )
    return screens


def parse_doc_screens(api_doc: str) -> set[str]:
    """Screen names declared in the docs/api.md '## Screen 枚举' table."""
    section = slice_section(api_doc, SCREEN_SECTION_HEADING, "docs/api.md")
    screens = set(DOC_SCREEN_ROW.findall(section))
    if not screens:
        raise GateError(
            "the docs/api.md '## Screen 枚举' table lists no screens, so the documented screen "
            "vocabulary cannot be checked."
        )
    return screens


def check_api_facts(repo_root: Path) -> list[str]:
    """Documented facts that a code constant owns must still agree with it."""
    notes: list[str] = []

    manifest = json.loads(read_text(repo_root, MANIFEST_VERSION_PATH))
    manifest_version = str(manifest.get("version", "")).strip()
    if not manifest_version:
        raise GateError(f"{MANIFEST_VERSION_PATH} carries no version to check docs/api.md against")

    api_doc = read_text(repo_root, "docs/api.md")

    documented_versions = MOD_VERSION_PATTERN.findall(api_doc)
    if not documented_versions:
        raise GateError(
            'docs/api.md no longer states a "mod_version" value, so the documented version '
            "cannot be checked against the manifest."
        )
    stale = sorted({value for value in documented_versions if value != manifest_version})
    if stale:
        raise GateError(
            "docs/api.md states mod_version " + ", ".join(stale) + " but " + MANIFEST_VERSION_PATH
            + " declares " + manifest_version + ". Update the docs/api.md example so it still "
            "describes the current build."
        )
    notes.append(f"docs/api.md mod_version {manifest_version} matches {MANIFEST_VERSION_PATH}")

    code_screens = parse_code_screens(repo_root)
    doc_screens = parse_doc_screens(api_doc)
    missing = sorted(code_screens - doc_screens)
    if missing:
        raise GateError(
            "GameStateService.ResolveNonModalScreen can emit screens missing from the docs/api.md "
            "'## Screen 枚举' table: " + ", ".join(missing) + ". Add them so clients can branch on "
            "the documented vocabulary."
        )
    notes.append(
        f"{len(code_screens)} screens from GameStateService.ResolveNonModalScreen all appear in "
        "the docs/api.md enum"
    )
    documented_only = sorted(doc_screens - code_screens)
    if documented_only:
        notes.append(
            "documented but not produced by ResolveNonModalScreen (expected for other producers): "
            + ", ".join(documented_only)
        )

    port_match = CODE_DEFAULT_PORT.search(read_text(repo_root, HTTP_SERVER_PATH))
    if not port_match:
        raise GateError(f"{HTTP_SERVER_PATH} no longer declares 'private const int DefaultPort = ...'")
    default_port = port_match.group(1)
    documented_ports = sorted(set(DOC_DEFAULT_PORT.findall(api_doc)))
    if not documented_ports:
        raise GateError(
            "docs/api.md no longer states the default listen port, so it cannot be checked against "
            f"{HTTP_SERVER_PATH}."
        )
    wrong_ports = sorted({port for port in documented_ports if port != default_port})
    if wrong_ports:
        raise GateError(
            "docs/api.md states default port " + ", ".join(wrong_ports) + " but " + HTTP_SERVER_PATH
            + " declares DefaultPort = " + default_port + ". Update the documented address."
        )
    notes.append(f"docs/api.md default port {default_port} matches {HTTP_SERVER_PATH} DefaultPort")

    return notes


def check_doc_marks(repo_root: Path) -> list[str]:
    notes: list[str] = []

    for path in sorted((repo_root / "docs").rglob("*.md")):
        relative = path.relative_to(repo_root).as_posix()
        if not DATED_DOC_PATTERN.search(path.name):
            continue
        text = path.read_text(encoding="utf-8")
        if not any(marker in text for marker in HISTORICAL_MARKERS):
            raise GateError(
                f"{relative} is a date-stamped record but carries no historical marker. Add a line containing "
                "'Historical snapshot' (or the Chinese equivalent) so the file cannot be mistaken for current state."
            )
        notes.append(f"{relative} marked as a snapshot")

    for relative, reason in REQUIRED_SNAPSHOT_MARKERS.items():
        text = read_text(repo_root, relative)
        if not any(marker in text for marker in HISTORICAL_MARKERS):
            raise GateError(
                f"{relative} is a point-in-time snapshot ({reason}) but carries no historical marker. "
                "Restore the marked header so it cannot be read as current state."
            )
        notes.append(f"{relative} marked as a snapshot")

    for relative, target in REQUIRED_REDIRECTS.items():
        text = read_text(repo_root, relative)
        if target not in text:
            raise GateError(
                f"{relative} must redirect to {target} so archived topic pages keep resolving. "
                "Restore the redirect line or update REQUIRED_REDIRECTS in this script."
            )
        notes.append(f"{relative} -> {target}")

    return notes


def list_tracked_docs(repo_root: Path) -> set[str]:
    """Paths under docs/ that the git index tracks, as repo-root-relative posix strings."""
    try:
        result = subprocess.run(
            # -z prints pathnames verbatim (no quoting), so non-ASCII filenames compare as-is.
            ["git", "-C", str(repo_root), "ls-files", "-z", "--", "docs"],
            capture_output=True,
            check=True,
        )
    except FileNotFoundError as exc:
        raise GateError(
            f"{repo_root} is a git work tree but 'git' could not be executed, so the "
            "docs/ tracking check cannot run. Install git or run this gate from a checkout."
        ) from exc
    except subprocess.CalledProcessError as exc:
        detail = exc.stderr.decode("utf-8", "replace").strip()
        raise GateError(f"'git ls-files' failed in {repo_root}: {detail}") from exc
    return {item for item in result.stdout.decode("utf-8", "replace").split("\0") if item}


def check_docs_tracked(repo_root: Path) -> list[str]:
    """Every Markdown page under docs/ must be tracked, so none can fall out of the repo."""
    if not (repo_root / ".git").exists():
        return [
            f"{repo_root} has no .git directory, so it is not a git work tree: "
            "skipping the docs/ tracking check"
        ]

    on_disk = sorted(
        path.relative_to(repo_root).as_posix()
        for path in (repo_root / "docs").rglob(DOCS_MARKDOWN_GLOB)
        if path.is_file()
    )
    if not on_disk:
        return ["docs/ holds no Markdown files to check"]

    tracked = list_tracked_docs(repo_root)
    untracked = [relative for relative in on_disk if relative not in tracked]
    if untracked:
        raise GateError(
            "these files exist under docs/ but git does not track them: "
            + ", ".join(untracked)
            + ". docs/ is no longer gitignored, so run 'git add' on them "
            "(docs/ 已不再被忽略，请 git add) -- a fresh checkout, and therefore CI, "
            "would not contain them."
        )
    return [f"all {len(on_disk)} Markdown pages under docs/ are tracked by git"]


def check_script_encoding(repo_root: Path) -> list[str]:
    notes: list[str] = []

    for pattern in SCRIPT_ENCODING_GLOBS:
        for path in sorted(repo_root.glob(pattern)):
            raw = path.read_bytes()
            relative = path.relative_to(repo_root).as_posix()
            if not any(byte > 0x7F for byte in raw):
                continue
            if not raw.startswith(UTF8_BOM):
                raise GateError(
                    f"{relative} contains non-ASCII text but has no UTF-8 BOM. Windows PowerShell 5.1 "
                    "would read it with the machine's ANSI code page, so the same bytes can decode "
                    "differently per locale and a stray quote character can break the whole script. "
                    "Save the file as UTF-8 with BOM."
                )
            notes.append(f"{relative} carries non-ASCII text with a UTF-8 BOM")

    return notes


GATES = {
    "lockfile": check_lockfile,
    "api-doc": check_api_doc,
    "api-facts": check_api_facts,
    "doc-marks": check_doc_marks,
    "docs-tracked": check_docs_tracked,
    "script-encoding": check_script_encoding,
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the offline verification gates.")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--only", choices=sorted(GATES), action="append", help="run only the named gate(s)")
    args = parser.parse_args()

    repo_root: Path = args.repo_root.resolve()
    missing = [name for name in ROOT_SENTINELS if not (repo_root / name).is_file()]
    if missing:
        print(
            f"verification gates failed: {repo_root} does not look like the repository root "
            f"(missing {', '.join(missing)})",
            file=sys.stderr,
        )
        return 1

    selected = args.only or sorted(GATES)
    try:
        for name in selected:
            notes = GATES[name](repo_root)
            print(f"[gate] {name}: ok")
            for note in notes:
                print(f"  - {note}")
    except GateError as exc:
        print(f"verification gates failed ({name}): {exc}", file=sys.stderr)
        return 1

    print(f"verification gates passed: {', '.join(selected)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
