#!/usr/bin/env python3
"""Offline verification gates for dependency security, API documentation, and archived docs.

Run from the repository root:

    python scripts/check_verification_gates.py
    python scripts/check_verification_gates.py --only api-doc

Gates
-----
lockfile   Dependency security floors plus manifest/lock agreement. Prevents the
           advisories closed for fastmcp (CVE-2026-32871) and fast-uri
           (CVE-2026-13676) from silently regressing on a future lock refresh.
api-doc    Every action the mod accepts in POST /action must appear in the
           action contract block in docs/api.md, and the block must not list
           actions the code no longer supports.
doc-marks  Date-stamped validation records must carry a historical marker, and
           archived topic pages must keep their redirect to history/.

Exit code 0 means every selected gate passed. Exit code 1 means at least one
gate failed and the failure detail has been printed to stderr. Standard library
only: preflight invokes this with the system Python.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# --- Gate configuration -----------------------------------------------------

# Minimum safe versions. Each entry names the advisory it protects against.
SECURITY_FLOORS: dict[str, tuple[str, str]] = {
    # package -> (minimum safe version, advisory)
    "fastmcp": ("3.2.0", "CVE-2026-32871 (issue #50)"),
    "fast-uri": ("3.1.6", "CVE-2026-13676 (issue #51)"),
}

# Locks are regenerated by tooling; these overrides must survive a refresh.
REQUIRED_NPM_OVERRIDES = {"yauzl": "3.2.1"}

API_CONTRACT_BEGIN = "<!-- BEGIN ACTION CONTRACT -->"
API_CONTRACT_END = "<!-- END ACTION CONTRACT -->"

# A date-stamped record inside docs/ is a snapshot, not a statement about today.
DATED_DOC_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}")
HISTORICAL_MARKERS = ("历史快照", "Historical snapshot")

# Archived topic pages keep their old path working as a redirect.
REQUIRED_REDIRECTS = {
    "docs/sts2-coverage-gaps.md": "history/sts2-coverage-gaps_2026-03-10.md",
}


class GateError(Exception):
    """A verification gate failed."""


def parse_version(value: str) -> tuple[int, ...]:
    parts: list[int] = []
    for chunk in re.split(r"[.\-+]", value.strip()):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts) if parts else (0,)


def version_at_least(actual: str, minimum: str) -> bool:
    left, right = list(parse_version(actual)), list(parse_version(minimum))
    width = max(len(left), len(right))
    left += [0] * (width - len(left))
    right += [0] * (width - len(right))
    return tuple(left) >= tuple(right)


def read_text(repo_root: Path, relative: str) -> str:
    path = repo_root / relative
    if not path.is_file():
        raise GateError(f"missing required file: {relative}")
    return path.read_text(encoding="utf-8")


def parse_uv_lock(text: str) -> dict[str, str]:
    packages: dict[str, str] = {}
    name: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == "[[package]]":
            name = None
            continue
        match = re.match(r'^name = "([^"]+)"$', stripped)
        if match:
            name = match.group(1)
            continue
        match = re.match(r'^version = "([^"]+)"$', stripped)
        if match and name:
            packages.setdefault(name, match.group(1))
    return packages


def parse_pyproject_dependencies(text: str) -> list[str]:
    match = re.search(r"(?ms)^dependencies = \[(.*?)^\]", text)
    if not match:
        return []
    return re.findall(r'"([^"]+)"', match.group(1))


def dependency_name(specifier: str) -> str:
    return re.split(r"[<>=!\[;]", specifier, maxsplit=1)[0].strip()


def flatten_overrides(overrides: dict) -> list[tuple[str, str]]:
    """npm overrides may be nested per parent package; flatten them to (package, pinned)."""
    flattened: list[tuple[str, str]] = []
    for key, value in overrides.items():
        if isinstance(value, str):
            flattened.append((key, value))
        elif isinstance(value, dict):
            flattened.extend(flatten_overrides(value))
    return flattened


def check_lockfile(repo_root: Path) -> list[str]:
    """Dependency floors and manifest/lock agreement."""
    notes: list[str] = []

    uv_lock = parse_uv_lock(read_text(repo_root, "mcp_server/uv.lock"))
    pyproject = read_text(repo_root, "mcp_server/pyproject.toml")

    for specifier in parse_pyproject_dependencies(pyproject):
        name = dependency_name(specifier)
        if name and name not in uv_lock:
            raise GateError(
                f"mcp_server/pyproject.toml declares '{name}' but mcp_server/uv.lock has no such package. "
                "Run 'uv lock' from mcp_server."
            )

    for package, (minimum, advisory) in SECURITY_FLOORS.items():
        if package not in uv_lock:
            continue
        actual = uv_lock[package]
        if not version_at_least(actual, minimum):
            raise GateError(
                f"mcp_server/uv.lock pins {package} {actual}, below the safe floor {minimum} ({advisory})."
            )
        notes.append(f"uv.lock {package} {actual} >= {minimum}")

    lock_path = repo_root / "package-lock.json"
    manifest_path = repo_root / "package.json"
    if lock_path.is_file() and manifest_path.is_file():
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
        packages = lock.get("packages", {})
        for package, (minimum, advisory) in SECURITY_FLOORS.items():
            entry = packages.get(f"node_modules/{package}")
            if entry is None:
                continue
            actual = str(entry.get("version", ""))
            if not version_at_least(actual, minimum):
                raise GateError(
                    f"package-lock.json pins {package} {actual}, below the safe floor {minimum} ({advisory})."
                )
            notes.append(f"package-lock.json {package} {actual} >= {minimum}")

        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        for package, pinned in flatten_overrides(manifest.get("overrides", {})):
            resolved = [
                str(entry.get("version", ""))
                for key, entry in packages.items()
                if re.search(rf"(^|/)node_modules/{re.escape(package)}$", key)
            ]
            if not resolved:
                raise GateError(
                    f"package.json overrides '{package}' to {pinned} but package-lock.json has no such entry."
                )
            below = sorted({item for item in resolved if not version_at_least(item, pinned)})
            if below:
                raise GateError(
                    f"package.json overrides '{package}' to {pinned} but package-lock.json still resolves {', '.join(below)}."
                )
            notes.append(f"override {package} {', '.join(sorted(set(resolved)))}")
            required = REQUIRED_NPM_OVERRIDES.get(package)
            if required and required not in resolved:
                raise GateError(
                    f"the required {package} override changed: expected {required}, package-lock.json resolves {', '.join(sorted(set(resolved)))}."
                )

    return notes


def parse_code_actions(repo_root: Path) -> set[str]:
    """Action names accepted by POST /action, read from the execute switch."""
    text = read_text(repo_root, "STS2AIAgent/Game/GameActionService.cs")
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if "return actionName switch" in line:
            start = index
            break
    if start is None:
        raise GateError("could not find 'return actionName switch' in STS2AIAgent/Game/GameActionService.cs")

    actions: set[str] = set()
    for line in lines[start + 1:]:
        if re.match(r"^\s*};\s*$", line):
            break
        match = re.match(r'^\s*"([a-z][a-z0-9_]*)"\s*=>', line)
        if match:
            actions.add(match.group(1))
    if not actions:
        raise GateError("the action switch in GameActionService.cs produced no action names")
    return actions


def parse_doc_actions(repo_root: Path) -> set[str]:
    """Action names declared in the docs/api.md contract block."""
    text = read_text(repo_root, "docs/api.md")
    begin = text.find(API_CONTRACT_BEGIN)
    end = text.find(API_CONTRACT_END)
    if begin < 0 or end < 0 or end <= begin:
        raise GateError(
            f"docs/api.md is missing the '{API_CONTRACT_BEGIN}' / '{API_CONTRACT_END}' action contract block."
        )
    block = text[begin + len(API_CONTRACT_BEGIN):end]
    actions = set(re.findall(r"^-\s*`([a-z][a-z0-9_]*)`", block, re.MULTILINE))
    if not actions:
        raise GateError("the docs/api.md action contract block lists no actions")
    return actions


def check_api_doc(repo_root: Path) -> list[str]:
    code = parse_code_actions(repo_root)
    documented = parse_doc_actions(repo_root)

    missing = sorted(code - documented)
    extra = sorted(documented - code)
    problems: list[str] = []
    if missing:
        problems.append("docs/api.md does not document these actions the mod accepts: " + ", ".join(missing))
    if extra:
        problems.append("docs/api.md documents these actions the mod does not accept: " + ", ".join(extra))
    if problems:
        raise GateError(" ".join(problems))
    return [f"{len(code)} actions match between GameActionService.cs and docs/api.md"]


def check_doc_marks(repo_root: Path) -> list[str]:
    notes: list[str] = []

    for path in sorted((repo_root / "docs").rglob("*.md")):
        relative = path.relative_to(repo_root).as_posix()
        if not DATED_DOC_PATTERN.search(path.name):
            continue
        text = path.read_text(encoding="utf-8")
        if not any(marker in text for marker in HISTORICAL_MARKERS):
            raise GateError(
                f"{relative} is a date-stamped record but carries no historical marker. Add a line containing "
                "'Historical snapshot' (or the Chinese equivalent) so the file cannot be mistaken for current state."
            )
        notes.append(f"{relative} marked as a snapshot")

    for relative, target in REQUIRED_REDIRECTS.items():
        text = read_text(repo_root, relative)
        if target not in text:
            raise GateError(
                f"{relative} must redirect to {target} so archived topic pages keep resolving. "
                "Restore the redirect line or update REQUIRED_REDIRECTS in this script."
            )
        notes.append(f"{relative} -> {target}")

    return notes


GATES = {
    "lockfile": check_lockfile,
    "api-doc": check_api_doc,
    "doc-marks": check_doc_marks,
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the offline verification gates.")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--only", choices=sorted(GATES), action="append", help="run only the named gate(s)")
    args = parser.parse_args()

    repo_root: Path = args.repo_root.resolve()
    if not (repo_root / "AGENTS.md").is_file():
        print(f"verification gates failed: {repo_root} does not look like the repository root", file=sys.stderr)
        return 1

    selected = args.only or sorted(GATES)
    try:
        for name in selected:
            notes = GATES[name](repo_root)
            print(f"[gate] {name}: ok")
            for note in notes:
                print(f"  - {note}")
    except GateError as exc:
        print(f"verification gates failed ({name}): {exc}", file=sys.stderr)
        return 1

    print(f"verification gates passed: {', '.join(selected)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
